### ISSUE TITLE
Maximize the screen size

### ISSUE THREAD

**Issue by wyatt-wong** [samkusin/clemens_iigs#102]
I found that after loading "Where in the USA is Carmen Sandiego" game in the emulator. The player screen is not fully maximized to be the same size as the emulator window.

![Screenshot 2023-04-09 at 12 04 15 AM](https://user-images.githubusercontent.com/10095648/230731291-5f736257-8222-47f8-94aa-54b1ddd67deb.png)

**Comment by samkusin** [comment]
This is a IIGS "feature" that the border area was not used (partially because of how NTSC works.).  Note the Apple II modes have a more extreme form of this.

Note this issue: #72 and how the border is colored.  In that case the self-diagnostics display sets this color for informational purposes.   But this option is also configurable in the IIGS Control Panel under the 'Display' section.

For example:
https://www.apl2bits.net/2010/12/27/iigs-review/

But I guess it might be nice to have an option to reduce this border area for emulation purposes.

**Comment by samkusin** [comment]
Added a mostly fullscreen mode in #133  - the blue border is a part of the machine's screen (the color can be changed in the control panel via control-command-F12.)
