### ISSUE TITLE
How to compile under macOS ?

### ISSUE THREAD

**Issue by wyatt-wong** [samkusin/clemens_iigs#79]
How to compile under macOS ?

**Comment by samkusin** [comment]
As you've noticed, the README isn't very clear on this.  The current state of main basically renders a lot of those instructions obsolete.   I'll update it - but to move you forward, you shouldn't need to perform any manual steps yourself.

When you start the application, you'll be prompted to locate a ROM file.  The application will take care of copying the file to your `~/Library/Application Support/cinekine/Clemens` folder, there the ROM file, BRAM (control panel settings), configuration and imported disks will be located.    You shouldn't need to manually copy anything with the current application.

**Comment by samkusin** [comment]
0.6 will be released early next week with an updated README and perhaps a couple small UI improvements.  SmartPort fixes should already be in main as of a couple hours ago.  

Let me know if you have any further questions and thanks for trying this out.

**Comment by samkusin** [comment]
Ok.  I think I see the problem on my end.  I've been testing by placing the app in a non system wide folder (I.e. running the app from the build folder.)

I'll run throw the flow you described and work on getting that to work.  It's the most common flow for end users as well.

**Comment by wyatt-wong** [comment]
> cmake -B build -DBUILD_TESTING=OFF

I downloaded the latest source and build it. Here is what I got:

<img width="1149" alt="Screenshot 2023-04-01 at 10 47 44 AM" src="https://user-images.githubusercontent.com/10095648/229262384-77304a7b-dfa5-40ee-8787-f0e92a3c358d.png">

<img width="1552" alt="Screenshot 2023-04-01 at 10 50 55 AM" src="https://user-images.githubusercontent.com/10095648/229262396-87fee1a9-483e-4b84-8e6e-5198ace78f5c.png">

<img width="1552" alt="Screenshot 2023-04-01 at 10 51 03 AM" src="https://user-images.githubusercontent.com/10095648/229262407-29c1e754-59e0-41cc-a9de-4629e7ee25d0.png">

**Comment by samkusin** [comment]
Thanks for these screenshots - they are helpful.   I'm not sure where that directory name `-psn_0_893156` is coming from (I assume you didn't select 'Change Directory' to get that.)

I'll add some additional logging around the area where the directory name is generated and selected during startup.   In the meantime, can you try running in the Terminal:

```
open '/Applications/Apple IIGS/Clemens IIGS.app'
```

Do you see the same behavior as above?   Also what happens if you do select 'Change Directory' and change it to a location in your home directory (i.e. `/Users/<your username>/Documents` or even a USB volume if you don't want to alter your local SSD.)

**Comment by wyatt-wong** [comment]
> open '/Applications/Apple IIGS/Clemens IIGS.app'

Here is what I got:

<img width="1552" alt="Screenshot 2023-04-01 at 3 43 46 PM" src="https://user-images.githubusercontent.com/10095648/229273295-4eb693b1-58aa-4521-aa69-1f46391cd21a.png">

<img width="1552" alt="Screenshot 2023-04-01 at 3 43 56 PM" src="https://user-images.githubusercontent.com/10095648/229273927-80252192-6774-4511-a033-5c9b8d72f4bd.png">

<img width="1552" alt="Screenshot 2023-04-01 at 3 44 04 PM" src="https://user-images.githubusercontent.com/10095648/229273949-2fe47cf1-ce68-49ac-b517-ec48eed37b59.png">

<img width="1552" alt="Screenshot 2023-04-01 at 3 44 13 PM" src="https://user-images.githubusercontent.com/10095648/229273963-d238ce5c-0ee2-4821-9ce3-91ed57dcdd29.png">

When I choose either a GS ROM 3 or do NOT choose GS ROM 3, the Clemens IIGS.app then quit immediately.

**Comment by wyatt-wong** [comment]
And even if I did not choose anything, why would the application display the directory name `-psn_0_893156` for me ?

**Comment by samkusin** [comment]
> And even if I did not choose anything, why would the application display the directory name `-psn_0_893156` for me ?

It looks like that `-psn_0_893156` value is being interpreted by the startup code as an application / command-line argument argument.  The code interpreting this is here: https://github.com/samkusin/clemens_iigs/blob/main/host/clem_host_app.cpp#L35

It's a rather sloppy method of allowing users to specify their own data directory if they didn't want to use the GUI and for debugging.  Now I don't know *why* this is happening as launching the app from `Applications` like that shouldn't inject command line arguments.     Since this feature has been superseded by other methods, I can take this out.

What's more concerning is the ROM issue.    If you browse `/Users/wyattwong/Documents/` do you see a folder called `cinekine`?   If so, can you check if there's anything in `/Users/wyattwong/Documents/cinekine/Clemens`.  You should see a `config.ini` file and also a ROM file there.

Can you send me the config.ini file if you have it?   Also if you launch the app from the Terminal, could you take a snapshot of any text output after running the app from there?

Thanks again for digging into this.   Though I haven't seen this behavior before, if it's happening to you. it'll likely happen to a sizeable enough slice of users.

**Comment by samkusin** [comment]
[Clemens IIGS.zip](https://github.com/samkusin/clemens_iigs/files/11131235/Clemens.IIGS.zip)

I've built and verified the app in the attached archive runs on a fresh install of Catalina (10.15.7).   The app was built on my M2 under Monterey with the following cmake configuration and build commands:

```
cd clemens_iigs
cmake -B build -DCMAKE_OSX_ARCHITECTURES="arm64;x86_64" -DCMAKE_OSX_DEPLOYMENT_TARGET=10.15 -DCMAKE_BUILD_TYPE=Release
cmake --build build --config=Release --target=clemens_iigs
```

If you're open to trying out this binary (I understand if not due to potential security concerns), can you verify this works on your device?   Note, there will be a `config.ini` file located in your `/Users/wyattwong/Library/Application Support/cinekine/Clemens` folder.   If you remove it, you should be greeted with the same introductory GUI as you described above.   I've also  in this build taken out the code I mentioned above that may be the source of that odd directory.

**Comment by wyatt-wong** [comment]
> [Clemens IIGS.zip](https://github.com/samkusin/clemens_iigs/files/11131235/Clemens.IIGS.zip)
> 
> 
> 
> I've built and verified the app in the attached archive runs on a fresh install of Catalina (10.15.7).   The app was built on my M2 under Monterey (Xcode 14 - but targeting Catalina) with the following cmake configuration and build commands:
> 
> 
> 
> ```
> 
> cd clemens_iigs
> 
> cmake -B build -DCMAKE_OSX_ARCHITECTURES="arm64;x86_64" -DCMAKE_OSX_DEPLOYMENT_TARGET=10.15 -DCMAKE_BUILD_TYPE=Release
> 
> cmake --build build --config=Release --target=clemens_iigs
> 
> ```
> 
> 
> 
> If you're open to trying out this binary (I understand if not due to potential security concerns), can you verify this works on your device?   Note, there will be a `config.ini` file located in your `/Users/wyattwong/Library/Application Support/cinekine/Clemens` folder.   If you remove it, you should be greeted with the same introductory GUI as you described above.   I've also  in this build taken out the code I mentioned above that may be the source of that odd directory.
> 
> 

I will rebuild it from source and test it later today. I am using the first generation of Retina MacBook Pro in Jun-2012 so I can't run your binaries.

**Comment by samkusin** [comment]
Ok.   I've pushed some changes in PR #85 just now to main (the specific host directory change is a one of the commits there.)  

If you do build and test the latest main today if you could run the build from your command line, can you send me any terminal output from the application?   I unfortunately don't have any Mac hardware older than the Retina MB Pro 2013 model.  

If you're on Catalina, then I think the GL libraries should support the 3.3 profile which this version requires.  Since you did see some GUI, I think you're OK on that side.

**Comment by wyatt-wong** [comment]
> /Users/wyattwong/Library/Application Support/cinekine/Clemens

I build it from the source and here is what I got:

<img width="1552" alt="Screenshot 2023-04-03 at 12 10 52 AM" src="https://user-images.githubusercontent.com/10095648/229365181-5b4f2d3f-e5d2-4adf-bbdc-2bb650a78605.png">

<img width="1552" alt="Screenshot 2023-04-03 at 12 08 51 AM" src="https://user-images.githubusercontent.com/10095648/229365189-9f07f6cc-1575-4dc9-a60a-054e743faef7.png">

I would say it is perfect for the time being except a small issue that I found Command+Q couldn't exit the application. The Command+Q should be a standard key combination across all macOS applications, I suppose.

Now I need explore how to startup the IIGS.

**Comment by samkusin** [comment]
Good to hear!  I'll close the issue as fixed for now.  I'll also look into adding that shortcut for quitting the app.  One concern I have is that the emulated machine may also need to handle that combination depending on the app.

**Comment by wyatt-wong** [comment]
> Good to hear! I'll close the issue as fixed for now. I'll also look into adding that shortcut for quitting the app. One concern I have is that the emulated machine may also need to handle that combination depending on the app.

I can't figure out how to start either ProDOS 2.4.2 or GS/OS, but that's another issue.

**Comment by samkusin** [comment]
If you've been able to attain disk images you can import them into the emulator by selecting one of the disk trays in the upper left part of the UI.   I think the help menu icon (question mark) has a summary of what's involved.

As for the Readme, it's going through a small rewrite which will be in the 0.6 release when done

**Comment by samkusin** [comment]
If you suggestions on UI improvements please feel free to submit issues for them.   They may make it into the 0.7 release if they aren't major changes.

**Comment by samkusin** [comment]
Again thank you for your patience.  It's always good to get user feedback as I'm currently the only one using this on almost a daily basis.

**Comment by wyatt-wong** [comment]
> If you've been able to attain disk images you can import them into the emulator by selecting one of the disk trays in the upper left part of the UI.   I think the help menu icon (question mark) has a summary of what's involved.
> 
> As for the Readme, it's going through a small rewrite which will be in the 0.6 release when done

I tried and it doesn't work.

First do I choose Disk 6 Slot 1, Disk 5 Slot 1 or the Smartport ?

I found the System 6.0.4 have a Live Install.po file so I assume I need to load it in Slot 5 Disk 1, but when I choose either Import Master Disk or Import Blank Disk option, the emulator will end up ask me to choose a destination and I found there is NONE in the dialog box for selection and I clicked Create Directory but got no response.

And the Smartport is pre-selected a .2mg file and I clicked on it and it doesn't allow me to load another .2mg file.

Maybe you should test it by yourself first. I felt I am like a beta tester rather than a normal user.

**Comment by samkusin** [comment]
I'm sorry that it's been this difficult to load your first disk.   Since I've been around this interface for months, what seems straightforward to me may not be to others as you've stated above. 

As mentioned earlier in the readme, this is basically alpha-level software and I'm a solo developer working on this as a hobby - which is about the story for most GitHub projects!

I think this is the roadblock you're seeing as the Live Install for System 6.0.4 is a 32MB hard disk image.    I assume you're seeing the same thing I am below what I try that.

<img width="1552" alt="Screen Shot 2023-04-02 at 7 06 48 PM" src="https://user-images.githubusercontent.com/1252669/229395622-a3d2422d-bd23-444f-9026-3fff4ddf140a.png">

Yes, the Smartport disk cannot be selected at this time.   It's a matter of adding the interface to switch out the disk and I'll add that to the list.  Probably having a separate "import disk" entry per disk slot is overly confusing.

Anyway, for now you can only use 3.5" and 5.25" disk images in Slots 5 and 6 respectively.   For example, you should see this when you use the System.Disk.po GSOS 800K image from I believe the same set of images that you have:

<img width="1552" alt="Screen Shot 2023-04-02 at 7 08 38 PM" src="https://user-images.githubusercontent.com/1252669/229400712-2d86eaaa-1cd8-4a4f-be0b-0d6f58a12cd6.png">

Then you select a location to place the imported disk image.   Basically the disk image is brought into your data directory's `library` folder under one of the subfolders you see in that list.   If there are no subfolders there, you would create a directory for it:

<img width="1552" alt="Screen Shot 2023-04-02 at 7 09 00 PM" src="https://user-images.githubusercontent.com/1252669/229400877-03dbc66b-6ee9-4703-afeb-d9c8508d3416.png">

*Finally* after clicking 'Create Directory' (or select an existing directory and press 'OK') you'll import the 800K 3.5" disk image:

<img width="1552" alt="Screen Shot 2023-04-02 at 7 09 05 PM" src="https://user-images.githubusercontent.com/1252669/229400925-99d310ea-42c2-40bd-9844-1b328c256e50.png">

Now you would select Slot 5, Drive and you should see the newly imported image:

<img width="1552" alt="Screen Shot 2023-04-02 at 7 45 36 PM" src="https://user-images.githubusercontent.com/1252669/229400939-6c9ce76a-1267-4873-929b-43522d6c2d2f.png">

And then reboot the machine (the cycle icon - yes this could be placed in a better location.)

<img width="1552" alt="Screen Shot 2023-04-02 at 7 46 12 PM" src="https://user-images.githubusercontent.com/1252669/229400946-7174d0ad-e8dc-44f9-aee8-41658f832278.png">
