### ISSUE TITLE
How to change the processor speed from 1 MHz to the default 2.8 MHz ?

### ISSUE THREAD

**Issue by wyatt-wong** [samkusin/clemens_iigs#99]
How to change the processor speed from 1 MHz to the default 2.8 MHz ?

**Comment by samkusin** [comment]
You'll need to enter the Apple IIGS control panel which contains a "System Speed" menu item (note, the default should be 2.8 mhz.)    In the Help section (main display - not the debugger display) there's a list of key combinations and their functions.

In this case, to enter the Control Panel you'll need to use the key combination (Ctrl + Option + F1) to enter the Control Panel. 

Note, the original Apple IIGS key combo was "Control-Option-Escape."   Since many OS's intercept Alt/Option + Escape key, most emulators have to provide alternatives (in this case F1)

**Comment by wyatt-wong** [comment]
This need to add into the documentation.

**Comment by samkusin** [comment]
That '1 Mhz' will be white (vs gray) when in 1mhz mode.     It might be more obvious if I just display the text if you're in 1mhz mode vs coloring it differently.

**Comment by samkusin** [comment]
The control panel is a IIGS feature built into the ROM vs an emulator feature that will show up when you press certain keys in combination.   On the original IIGS, the key combination was Option-Control-Escape.   You would use Option-Control-F1 (for mac keyboards you may have to press the Fn key as well to trigger F1 vs brightness control.)

I've thought about creating menu items or switches that trigger these key combinations automatically since they can be difficult to get right on some keyboards.

**Comment by wyatt-wong** [comment]
The game seems to running in a slower speed than an Apple II emulator. But IIGS should run at 2.8MHz if I was not mistaken.
